# -*- coding: utf-8 -*-
"""sports_data_connection_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv2Yw7XD1tC5p132ioz3YqWTY9JMgqmN
"""

#pymysql, sqlalchemy, pandas, python-dotenv

from sqlalchemy import create_engine
import pandas as pd

import os
from dotenv import load_dotenv

load_dotenv()

sql_username = os.getenv('username')
sql_password = os.getenv('password')
sql_host = os.getenv ('hostname')
sql_database = os.getenv ('database')

sql_username

# with SSL off
url_string = f"mysql+pymysql://{sql_username}:{sql_password}@{sql_host}:3306/{sql_database}"

conn = create_engine(url_string)

sql_toexecute = """
  select *
  from research_experiment_refactor_test limit 50;
  """

response = pd.read_sql(sql_toexecute, conn)
response